config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  get 'index/index'
  get 'students/home', to: 'students#home', as: :student_home
  get 'teachers/home'
  
  get 'students/all' => 'students#index'
  get 'teachers/all' => 'teachers#index'

  get 'students/show' => 'students#show'
  
  get 'subjects/photos/:id' => 'subjects#photos'
  

  devise_for :students
  devise_for :teachers

  resources :events
  resources :subjects
  resources :students
  resources :teachers

  mount Resque::Server.new, at: "/resque"

  root to: 'index#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :subject
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @subjects = Subject.all

  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.all
    @subjects = Subject.all
  end

  # GET /events/new
  def new
    @event = Event.new
    @subjects = Subject.all

  end

  # GET /events/1/edit
  def edit
    @events = Event.all
    @subjects = Subject.all
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @subjects = Subject.all


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:subject_id, :capture_interval, :duration, :start, :repeat, :ip, :day)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<html>
  
<body id="home">
  <% if student_signed_in? || teacher_signed_in? %>
  	<header class="navbar navbar-inverse hero" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-right">
      				<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Matérias<b class="caret"></b></a>
          			<ul class="dropdown-menu">
          	  	  <% @subject.each do |subject| %>
                    <li><a href="/subjects/photos/<%= subject.id %>" class="list-group-item" ><%= subject.name %></a></li>
                  <% end %>
							  </ul>
        			</li>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Eventos<b class="caret"></b></a>
          				<ul class="dropdown-menu">
							<li><a href="/events">Eventos registrados</a></li>
							<li><a href="/events/new">Criar evento</a></li>
				        </ul>
        			</li>
        			
        			</ul>
        			</li>
        			
      			</ul>
    		</nav>
  		</div>
	</header>
	<% else %>
	  <header class="navbar navbar-inverse hero" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
      			<a href="#" class="navbar-brand">Home</a>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-right">
      				<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Sign up <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="/students/sign_up">Aluno</a></li>
							<li><a href="/teachers/sign_up">Professor</a></li>
							  </ul>
        			</li>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Sign in <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="/students/sign_in">Aluno</a></li>
							<li><a href="/teachers/sign_in">Professor</a></li>
				        </ul>
        			</li>
        			<li>
        				<a href="http://ort.org.br">ORT</a>
        			</li>
        			<li>
        				<a href="https://bitbucket.org/gabihecksher/omniboard">Bitbucket</a>
        			</li>
      			</ul>
    		</nav>
  		</div>
	  </header>  
	<% end %>



	<div id="hero">
		<div class="container">
        <%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>
  <div class="field">
    <%= f.label :capture_interval %><br>
    <%= f.number_field :capture_interval %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
			<div class="img"></div>
		</div>
	</div>


</body>
</html>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<html>
  
<style>
  body{
    color: #fff;
  }
</style>
<body id="home">
  <% if student_signed_in? || teacher_signed_in? %>
  	<header class="navbar navbar-inverse hero" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-right">
      				<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Matérias<b class="caret"></b></a>
          			<ul class="dropdown-menu">
          	  	  <% @subjects.each do |subject| %>
                    <li><a href="/subjects/photos/<%= subject.id %>" class="list-group-item" ><%= subject.name %></a></li>
                  <% end %>
							  </ul>
        			</li>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Eventos<b class="caret"></b></a>
          				<ul class="dropdown-menu">
							<li><a href="/events">Eventos registrados</a></li>
							<li><a href="/events/new">Criar evento</a></li>
				        </ul>
        			</li>
        			
        			</ul>
        			</li>
        			
      			</ul>
    		</nav>
  		</div>
	</header>
	<% else %>
	  <header class="navbar navbar-inverse hero" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
      			<a href="#" class="navbar-brand">Home</a>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-right">
      				<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Sign up <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="/students/sign_up">Aluno</a></li>
							<li><a href="/teachers/sign_up">Professor</a></li>
							  </ul>
        			</li>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
          					Sign in <b class="caret"></b>
          				</a>
          				<ul class="dropdown-menu">
							<li><a href="/students/sign_in">Aluno</a></li>
							<li><a href="/teachers/sign_in">Professor</a></li>
				        </ul>
        			</li>
        			<li>
        				<a href="http://ort.org.br">ORT</a>
        			</li>
        			<li>
        				<a href="https://bitbucket.org/gabihecksher/omniboard">Bitbucket</a>
        			</li>
      			</ul>
    		</nav>
  		</div>
	  </header>  
	<% end %>



	<div id="hero">
		<div class="container">
			
<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Capture Interval</th>
      <th>Duration</th>
      <th>Start</th>
      <th>Day</th>
      <th>Ip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.subject_id %></td>
        <td><%= event.capture_interval %></td>
        <td><%= event.duration %></td>
        <td><%= event.start %></td>
        <td><%= event.day %></td>
        <td><%= event.ip %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

			<div class="img"></div>
		</div>
	</div>







<br>

</body>
</html>
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<style>
    body {
      color: white;
    }
    form input{
      color: black;
    }
  </style>
<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @event.subject_id %>
</p>

<p>
  <strong>Capture interval:</strong>
  <%= @event.capture_interval %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>Day:</strong>
  <%= @event.day %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @event.ip %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>