config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  get 'index/index'
  get 'students/home', to: 'students#home', as: :student_home
  get 'teachers/home'
  
  get 'students/all' => 'students#index'
  get 'teachers/all' => 'teachers#index'

  get 'students/show' => 'students#show'
  
  get 'subjects/photos/:id' => 'subjects#photos'
  

  devise_for :students
  devise_for :teachers

  resources :events
  resources :subjects
  resources :students
  resources :teachers

  mount Resque::Server.new, at: "/resque"

  root to: 'index#index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
    belongs_to :teacher
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy, :photos]

  # GET /subjects
  # GET /subjects.json
  def index
    if teacher_signed_in?
      @subjects = current_teacher.subjects
    else
      @subjects = Subject.all
    end
      @teachers = Teacher.all
  end
  
  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  
  # GET /subjects/new
  def new
    @subject = Subject.new
    @teachers = Teacher.all
  end

  # GET /subjects/1/edit
  def edit
    @subjects = Subject.all
    @teachers = Teacher.all
  end
  
  def photos
    diretorio = "#{ENV['DB_PHOTO_PATH']}/#{@subject.name}/*.jpg"
    my_files = Dir.glob(diretorio).map { |f| File.basename(f) }
    @arquivos = Kaminari.paginate_array(my_files.reverse).page(params[:page]).per(6)
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :grade, :time, :weekday)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  
  <div class="field">
    <%= f.label :weekday %><br>
    <%= f.text_field :weekday %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<style>
   
    body {
      color: white;
    }
    form input {
	color: black;
	}
</style>
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Grade</th>
      <th>Time</th>
      <th>Weekday</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.grade %></td>
        <td><%= subject.time %></td>
        <td><%= subject.weekday %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Photos', "/subjects/photos/#{subject.id}" %></td>
      </tr>
      
      
      
    <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<style>
    body {
      color: white;
    }
    form input{
      color: black;
    }
  </style>
<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/photos.html.erb
<html>
  <style>
   
    body {
      color: white;
    }
    input {
	color: black;
	}
</style>

<body id='home'>
<header class="navbar navbar-inverse hero" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-right">
      				<% if student_signed_in? %>
      				    <li class="dropdown">
        				    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_student.name %><b class="caret"></b></a>
          				    <ul class="dropdown-menu">
						    	<li><a href="/students/home">Minha página</a></li>
				            </ul>
        		    	</li>
        		    <% end %>
        		    <% if teacher_signed_in? %>
      				    <li class="dropdown">
        				    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_teacher.name %><b class="caret"></b></a>
          				    <ul class="dropdown-menu">
						    	<li><a href="/teachers/home">Minha página</a></li>
				            </ul>
        		    	</li>
        		    <% end %>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Eventos<b class="caret"></b></a>
          				<ul class="dropdown-menu">
							<li><a href="/events">Eventos registrados</a></li>
							<li><a href="/events/new">Criar evento</a></li>
				        </ul>
        			</li>
        			
        			</ul>
        			</li>
        			
      			</ul>
    		</nav>
  		</div>
	</header>

	<div id="hero">
		<div class="container">

    <h1><%= @subject.name %></h1>

    </div>
  </div>
  <%= paginate @arquivos %>
    <p>
        <% @arquivos.each do |arquivo| %>
            <img src="/<%= @subject.name %>/<%= arquivo %>" style="padding: 25px 50px 75px 100px;">
            
        <% end %>
    </p>
  </body>
</html>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @subject.grade %>
</p>

<p>
  <strong>Time:</strong>
  <%= @subject.time %>
</p>

<p>
  <strong>Weekday:</strong>
  <%= @subject.weekday %>
</p>


<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>