config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  get 'index/index'
  get 'students/home', to: 'students#home', as: :student_home
  get 'teachers/home'
  
  get 'students/all' => 'students#index'
  get 'teachers/all' => 'teachers#index'

  get 'students/show' => 'students#show'
  
  get 'subjects/photos/:id' => 'subjects#photos'
  

  devise_for :students
  devise_for :teachers

  resources :events
  resources :subjects
  resources :students
  resources :teachers

  mount Resque::Server.new, at: "/resque"

  root to: 'index#index'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :subjects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    
    has_attached_file :avatar, :styles => { :thumb => "200x200#" },
    :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
    :url => "/system/:attachment/:id/:basename_:style.:extension",
    :styles => {
      :thumb    => ['100x100#',  :jpg, :quality => 70],
      :preview  => ['480x480#',  :jpg, :quality => 70],
      :large    => ['600>',      :jpg, :quality => 70],
      :retina   => ['1200>',     :jpg, :quality => 30]
    },
    :convert_options => {
      :thumb    => '-set colorspace sRGB -strip',
      :preview  => '-set colorspace sRGB -strip',
      :large    => '-set colorspace sRGB -strip',
      :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
    }
    
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
# before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher!, except: [:index]


  def home
    @teachers = Teacher.all
    @subjects = Subject.all
  end
  
  
  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
    @subjects = Subject.all
  end


  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @subjects = Subject.all
  end

  # GET /teachers/new
  def new
    byebug
    @teacher = Teacher.new
    @subjects = Subject.all
  end

  # GET /teachers/1/edit
  def edit
    @subjects = Subject.all
  end
  
  def home
    @teacher = current_teacher
    @subjects = Subject.all
  end

  # POST /teachers
  # POST /teachers.json
  def create
    byebug
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|

      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      byebug
      params.require(:teacher).permit(:name, :email, :avatar)
    end
    
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/home.html.erb
<html>
<style>
    .ibagem{
      padding:0 0 0 850px;
      border-radius: 50%; 
    }
    .ibagem img{
      height: 150px;
      width: auto;
    }

</style>
   
<body id="home">
	<header class="navbar navbar-inverse hero" role="banner">
  		<div class="container">
    		<div class="navbar-header">
		      	<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
    		</div>
    		<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      			<ul class="nav navbar-nav navbar-right">
      				<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Matérias<b class="caret"></b></a>
          			<ul class="dropdown-menu">
          	  	  <% @subjects.each do |subject| %>
                    <li><a href="/subjects/photos/<%= subject.id %>" class="list-group-item" ><%= subject.name %></a></li>
                  <% end %>
							  </ul>
        			</li>
        			<li class="dropdown">
        				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Eventos<b class="caret"></b></a>
          				<ul class="dropdown-menu">
							<li><a href="/events">Eventos registrados</a></li>

				        </ul>
        			</li>
        			
        			
      			</ul>
    		</nav>
  		</div>
	</header>

	<div id="hero">
		<div class="container">
			
<div class="col-md-3">
  <ul class="nav nav-pills nav-stacked">
    <li class='ibagem'><%= image_tag current_teacher.avatar.url, class:"img-circle" %></li>
  </ul>
</div>
			<div class="img"></div>
		</div>
	</div>


</body>

</html>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subjects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td>

        
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href="teachers/sign_up">New teacher</a>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>
<!--
<p>
  <strong>Subjects:</strong>
  <%= @teacher.subjects.map{|s| s.name}.join(", ") %>
</p>
-->
<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>